package com.main.transaction.enums;

public enum TransactionType {
    FUND_TRANSFER,
	PHONE_TOP_UP,
	BILL_PAYMENT,
	HOST_TO_HOST,
	CASH_BACK,
	LINK_PARTNER_ACCOUNT,
	VNPOST_CASHOUT,
	E_REQUEST,
	EARLY_DISCHARGE_LOAN,
	CEPL_ORDER,
	DEPOSIT_WITHDRAWAL,
	E_WALLET_OD_PURCHASING,
	OD_REPAYMENT,
	E_WALLET_OD_INSTALLMENT,
	CASH_WITHDRAWAL,
	HYSS_WITHDRAWAL,
	FUND_IN,
	FUND_OUT,
	OD_PURCHASING,
	E_WALLET_OD_PURCHASING_VENDOR,
	CARD_TRANSACTION,
	E_WALLET_OD_INSTALLMENT_VENDOR;
}
